# .travis.yml
sudo: required

language: node_js

services:
  - docker

node_js:
  - '8'
branches:
  only:
    - master

cache:
  yarn: true

before_install:
- docker pull lucascst/gh-pages-docker-travis
- docker run -d -p 3000:3000 lucascst/gh-pages-docker-travis bash
- docker ps -a
# - docker run lucascst/gh-pages-docker-travis bash -c "cd /app/docs; bundle exec rake test"

script:
  - docker run lucascst/gh-pages-docker-travis bash -c "cd docs; sh publish.sh"

