# .travis.yml
sudo: required

language: node_js

services:
  - docker

node_js:
  - '8'
branches:
  only:
    - master

cache:
  yarn: true

before_install:
  - docker pull lucascst/gh-pages-docker-travis

script:
  - echo "GH_NAME=lucasca73" >> docs/.env
  - echo "GH_EMAIL=${GH_EMAIL}" >> docs/.env
  - echo "GH_TOKEN=${GH_TOKEN}" >> docs/.env
  - cat docs/.env
  - if [ ${TRAVIS_PULL_REQUEST} = 'true' ]; then docker run -v `pwd`:"/app" -w "/app" --env-file docs/.env lucascst/gh-pages-docker-travis bash -c "cd docs; sh publish.sh"; fi

