# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - npm i yarn -g
  # - yarn install
  - yarn global add docusaurus-init && npm install --global docusaurus-init
  - cd docs/website
  - GIT_USER=${GH_NAME} yarn run publish-gh-pages