# .travis.yml
sudo: required

language: node_js

services:
  - docker

node_js:
  - '8'
branches:
  only:
    - master

cache:
  yarn: true

before_install:
  - docker pull lucascst/gh-pages-docker-travis

script:
  - docker run -v `pwd`:"/app" -w "/app" lucascst/gh-pages-docker-travis bash -c "cd docs; sh publish.sh"

